# Default values for wordpress-site.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# Uncomment to use a custom image
global:
  image:
    {}
    # repository: docker.io/bitpoke/wordpress-runtime
    # tag: latest
    # pullPolicy: IfNotPresent
  # imagePullSecrets: ImagePullSecretName

  site:
    domains: {}
    env: []
    envFrom: []
    resources: {}
    # to automatically install wordpress
    # bootstrap:
    # title: Demo site
    # email: ping@<your domain name>
    # user:
    # password:

  tls:
    {}
    # issuerKind: ClusterIssuer
    # issuerName: wp-manager-stack-default-certificate-issuer
  # acmeChallengeType: http01

  code:
    # when true, the code is mounted read-only inside the runtime container
    readOnly: false

    # the path, within the code volume (git repo), where the 'wp-content' is
    # available
    contentSubPath: wp-content/
    uploadSubPath: wp-content/uploads/
    db:
      encryption_key:
      encrypt_db_export:
    git:
      repository:
      reference:
      github_app_secret:
      use_github_app:
      use_ssh_key:

  staging:
    # when true, the code is mounted read-only inside the runtime container
    readOnly: false
    create_staging_env: false
    # the path, within the code volume (git repo), where the 'wp-content' is
    # available
    git:
      reference:



    #  git:
    #    repository: git@github.com/bitpoke/wordpress-basic-demo
    #    reference: "3df6701bd06d97a3954b18625926753f6246c266"
    #    # it is not recommended to use a 'moving' target for deployment like a
    #    # branch name. You should use a specific commit or a git tag.
    #    # reference: master

  media:
    {}
    #  Store media library in a Google Cloud Storage bucket
    #  gcs:
    #    # google cloud project
    #    project: staging
    #    # bucket name
    #    bucket: calins-wordpress-runtime-playground
    #    # use a prefix inside the bucket to store the media files
    #    prefix: mysite/
    #    # credentials to access Google Cloud Storage
  #    google_credentials: >

  mysql:
    mysqlConf: {}
    replicaCount: 1

  memcached:
    enabled: false
