apiVersion: wordpress.presslabs.org/v1alpha1
kind: Wordpress
metadata:
  name: {{ include "wordpress-site.fullname" . }}-stg
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/part-of: wordpress
    helm.sh/chart: {{ include "wordpress-site.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.global.replicaCount }}
  {{- if .Values.global.image.repository }}
  {{- if (hasPrefix "@sha1" (default "latest" .Values.global.image.tag)) }}
  image: {{ .Values.global.image.repository }}{{ .Values.global.image.tag }}
  {{- else }}
  image: {{ .Values.global.image.repository }}:{{ default "latest" .Values.global.image.tag }}
  {{- end }}
  {{- end }}
  {{ if .Values.global.image.pullPolicy }}
  imagePullPolicy: {{ .Values.global.image.pullPolicy }}
  {{- end }}
  {{- if .Values.global.image.imagePullSecrets }}
  imagePullSecrets: {{ .Values.global.image.imagePullSecrets }}
  {{- end }}
  domains:
    - {{ required "A valid domain needs to be specified for staging env!" .Values.global.staging.domains.first }}
    {{- if .Values.global.staging.domains.second }}
    - {{ .Values.global.staging.domains.second }}
    {{- end }}
    {{- if .Values.global.staging.domains.third }}
    - {{ .Values.global.staging.domains.third }}
    {{- end }}
    {{- if .Values.global.staging.domains.forth }}
    - {{ .Values.global.staging.domains.forth }}
    {{- end }}
    {{- if .Values.global.staging.domains.fifth }}
    - {{ .Values.global.staging.domains.fifth }}
    {{- end }}
  tlsSecretRef: {{ include "wordpress-site.fullname" . }}-stg-tls
  {{- if .Values.global.code }}
  code:
    readOnly: {{ .Values.global.code.readOnly }}
    contentSubPath: {{ .Values.global.code.contentSubPath }}
    {{- if .Values.global.code.git }}
    git:
      repository: {{ default "https://github.com/Hubelia/wordpress-base" .Values.global.code.git.repository | quote }}
      reference: {{ default "main" .Values.global.staging.git.reference }}
      env:
        - name: DB_HOST
          value: {{ include "wordpress-site.fullname" . }}-stg-mysql-master
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "wordpress-site.fullname" . }}-stg-db
              key: PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: {{ include "wordpress-site.fullname" . }}-stg-db
              key: DATABASE
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "wordpress-site.fullname" . }}-stg-db
              key: USER
        {{- if .Values.global.code.git.ssh_private_key }}
        - name: SSH_RSA_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "wordpress-site.fullname" . }}-stg
              key: id_rsa
              optional: true
        {{- end }}
        {{- if .Values.global.code.git.use_github_app }}
        - name: GITHUB_APP_ID
          valueFrom:
            secretKeyRef:
              name: {{ template "wordpress-site.git_app_secret" . }}
              key: app_id
              optional: true
        - name: GITHUB_APP_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "wordpress-site.git_app_secret" . }}
              key: private_key
              optional: true
        {{- end }}
        {{- if .Values.global.code.db.encrypt_db_export }}
        - name: DB_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "wordpress-site.db_encryption_key" . }}
              key: encryption_key
              optional: true
        {{- end }}
        - name: WP_ENV
          value: 'staging'
    {{- end }}
  {{- end }}
  {{- if and .Values.global.media .Values.global.media.gcs }}
  media:
    gcs:
      bucket: {{ required "A valid media.gcs.bucket is required!" .Values.global.media.gcs.bucket | quote }}
      prefix: {{ default "" .Values.global.media.gcs.prefix | quote }}
      env:
        - name: GOOGLE_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: {{ include "wordpress-site.fullname" . }}-stg
              key: google_application_credentials.json
        - name: GOOGLE_PROJECT_ID
          value: {{ required "A valid media.gcs.project is required!" .Values.global.media.gcs.project | quote }}
  {{- end }}
  env:
    - name: DB_HOST
      value: {{ include "wordpress-site.fullname" . }}-stg-mysql-master
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: {{ include "wordpress-site.fullname" . }}-stg-db
          key: USER
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: {{ include "wordpress-site.fullname" . }}-stg-db
          key: PASSWORD
    - name: DB_NAME
      valueFrom:
        secretKeyRef:
          name: {{ include "wordpress-site.fullname" . }}-stg-db
          key: DATABASE
  {{- if .Values.global.site.env }}
    {{- toYaml .Values.global.site.env | nindent 4 }}
  {{- end }}
  {{- if .Values.global.site.envFrom }}
  envFrom:
    {{- toYaml .Values.global.site.envFrom | nindent 4 }}
  {{- end }}
  {{- if .Values.global.site.resources.override }}
  resources:
    limits:
      cpu: {{ default "400m" .Values.global.site.resources.limits.cpu }}
      memory: {{ default "768Mi" .Values.global.site.resources.limits.memory }}
    requests:
      cpu: {{ default "200m" .Values.global.site.resources.requests.cpu }}
      memory: {{ default "512Mi" .Values.global.site.resources.requests.memory }}
  {{- else }}
  resources:
    limits:
      cpu: 400m
      memory: 768Mi
    requests:
      cpu: 200m
      memory: 512Mi
  {{- end }}

  {{- if .Values.global.site.bootstrap.enabled }}
  bootstrap:
    {{- if .Values.global.site.bootstrap.password }}
    envFrom:
      - secretRef:
          name: {{ include "wordpress-site.fullname" . }}-stg-bootstrap
    {{- end }}
    {{- if .Values.global.site.bootstrap.old_url }}
    env:
      - name: WORDPRESS_BOOTSTRAP_OLD_URL
        value: {{ .Values.global.site.bootstrap.old_url | b64enc | quote }}
    {{- end }}
  {{- end }}

  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: node-role.stack.bitpoke.org/wordpress
            operator: Exists
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: wordpress
              app.kubernetes.io/instance: {{ .Release.Name }}
              app.kubernetes.io/part-of: wordpress
  tolerations:
    - key: "cloud.google.com/gke-preemptible"
      operator: "Exists"
  ingressAnnotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    {{- if eq "ClusterIssuer" (default "ClusterIssuer" .Values.global.tls.issuerKind) }}
    certmanager.k8s.io/cluster-issuer: {{ default "stack-default-certificate-issuer" .Values.global.tls.issuerName }}
    cert-manager.io/cluster-issuer: {{ default "stack-default-certificate-issuer" .Values.global.tls.issuerName }}
    {{- else if eq "Issuer" (default "ClusterIssuer" .Values.global.tls.issuerKind) }}
    certmanager.k8s.io/issuer: {{ default "stack-default-certificate-issuer" .Values.global.tls.issuerName }}
    cert-manager.io/issuer: {{ default "stack-default-certificate-issuer" .Values.global.tls.issuerName }}
    {{- end }}
    certmanager.k8s.io/acme-challenge-type: {{ default "http01" .Values.global.tls.acmeChallengeType }}
