apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: {{ include "wordpress-site.fullname" . }}-stg
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/part-of: wordpress
    helm.sh/chart: {{ include "wordpress-site.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.global.mysql.replicaCount }}
  secretName: {{ include "wordpress-site.fullname" . }}-stg-db
  mysqlConf:
    {{ toYaml .Values.global.mysql.mysqlConf | nindent 4 }}
  {{- if .Values.global.mysql.storageSize }}
  volumeSpec:
    persistentVolumeClaim:
      resources:
        requests:
          storage: {{ .Values.global.mysql.storageSize }}
  {{- end }}
