apiVersion: wordpress.presslabs.org/v1alpha1
kind: Wordpress
metadata:
  name: {{ include "wordpress-site.fullname" . }}
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/part-of: wordpress
    helm.sh/chart: {{ include "wordpress-site.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- if .Values.image.repository }}
  {{- if (hasPrefix "@sha1" (default "latest" .Values.image.tag)) }}
  image: {{ .Values.image.repository }}{{ .Values.image.tag }}
  {{- else }}
  image: {{ .Values.image.repository }}:{{ default "latest" .Values.image.tag }}
  {{- end }}
  {{- end }}
  {{ if .Values.image.pullPolicy }}
  imagePullPolicy: {{ .Values.image.pullPolicy }}
  {{- end }}
  {{- if .Values.image.imagePullSecrets }}
  imagePullSecrets: {{ .Values.image.imagePullSecrets }}
  {{- end }}
  domains:
    - {{ .Values.site.domains.first }}
    {{- if .Values.site.domains.second }}
    - {{ .Values.site.domains.second }}
    {{- end }}
    {{- if .Values.site.domains.third }}
    - {{ .Values.site.domains.third }}
    {{- end }}
    {{- if .Values.site.domains.forth }}
    - {{ .Values.site.domains.forth }}
    {{- end }}
    {{- if .Values.site.domains.fifth }}
    - {{ .Values.site.domains.fifth }}
    {{- end }}
  tlsSecretRef: {{ include "wordpress-site.fullname" . }}-tls
  {{- if .Values.code }}
  code:
    readOnly: {{ .Values.code.readOnly }}
    contentSubPath: {{ .Values.code.contentSubPath }}
    {{- if .Values.code.git }}
    git:
      repository: {{ default "https://github.com/Hubelia/wordpress-base" .Values.code.git.repository | quote }}
      reference: {{ default "main" .Values.code.git.reference }}
      env:
        - name: HOLA_COLADA
          value: hola
      - name: DB_USER
        valueFrom:
          secretKeyRef:
            name: {{ include "wordpress-site.fullname" . }}-db
            key: USER
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: {{ include "wordpress-site.fullname" . }}-db
            key: PASSWORD
      - name: DB_NAME
        valueFrom:
          secretKeyRef:
            name: {{ include "wordpress-site.fullname" . }}-db
            key: DATABASE
        {{- if .Values.code.git.ssh_private_key }}
        - name: SSH_RSA_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "wordpress-site.fullname" . }}
              key: id_rsa
              optional: true
        {{- end }}
        {{- if .Values.code.git.use_github_app }}
        - name: GITHUB_APP_ID
          valueFrom:
            secretKeyRef:
              name: {{ template "wordpress-site.git_app_secret" . }}
              key: app_id
              optional: true
        - name: GITHUB_APP_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "wordpress-site.git_app_secret" . }}
              key: private_key
              optional: true
        {{- end }}
        {{- if .Values.code.git.encrypted_db_export }}
          - name: DB_ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: {{ template "wordpress-site.db_encryption_key" . }}
                key: encryption_key
                optional: true
        {{- end }}
    {{- end }}
  {{- end }}
  {{- if and .Values.media .Values.media.gcs }}
  media:
    gcs:
      bucket: {{ required "A valid media.gcs.bucket is required!" .Values.media.gcs.bucket | quote }}
      prefix: {{ default "" .Values.media.gcs.prefix | quote }}
      env:
        - name: GOOGLE_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: {{ include "wordpress-site.fullname" . }}
              key: google_application_credentials.json
        - name: GOOGLE_PROJECT_ID
          value: {{ required "A valid media.gcs.project is required!" .Values.media.gcs.project | quote }}
  {{- end }}
  env:
    - name: MEMCACHED_DISCOVERY_HOST
      value: {{ include "wordpress-site.fullname" . }}-memcached
    - name: DB_HOST
      value: {{ include "wordpress-site.fullname" . }}-mysql-master
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: {{ include "wordpress-site.fullname" . }}-db
          key: USER
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: {{ include "wordpress-site.fullname" . }}-db
          key: PASSWORD
    - name: DB_NAME
      valueFrom:
        secretKeyRef:
          name: {{ include "wordpress-site.fullname" . }}-db
          key: DATABASE
  {{- if .Values.site.env }}
    {{- toYaml .Values.site.env | nindent 4 }}
  {{- end }}
  {{- if .Values.site.envFrom }}
  envFrom:
    {{- toYaml .Values.site.envFrom | nindent 4 }}
  {{- end }}
  {{- if .Values.site.resources.override }}
  resources:
    limits:
      cpu: {{ default "400m" .Values.site.resources.limits.cpu }}
      memory: {{ default "768Mi" .Values.site.resources.limits.memory }}
    requests:
      cpu: {{ default "200m" .Values.site.resources.requests.cpu }}
      memory: {{ default "512Mi" .Values.site.resources.requests.memory }}
  {{- else }}
  resources:
    limits:
      cpu: 400m
      memory: 768Mi
    requests:
      cpu: 200m
      memory: 512Mi
  {{- end }}

  {{- if .Values.site.bootstrap }}
  bootstrap:
    envFrom:
      - secretRef:
          name: {{ include "wordpress-site.fullname" . }}-bootstrap
  {{- end }}

  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: node-role.stack.bitpoke.org/wordpress
            operator: Exists
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: wordpress
              app.kubernetes.io/instance: {{ .Release.Name }}
              app.kubernetes.io/part-of: wordpress
  tolerations:
    - key: "cloud.google.com/gke-preemptible"
      operator: "Exists"
  ingressAnnotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    {{- if eq "ClusterIssuer" (default "ClusterIssuer" .Values.tls.issuerKind) }}
    certmanager.k8s.io/cluster-issuer: {{ default "stack-default-certificate-issuer" .Values.tls.issuerName }}
    cert-manager.io/cluster-issuer: {{ default "stack-default-certificate-issuer" .Values.tls.issuerName }}
    {{- else if eq "Issuer" (default "ClusterIssuer" .Values.tls.issuerKind) }}
    certmanager.k8s.io/issuer: {{ default "stack-default-certificate-issuer" .Values.tls.issuerName }}
    cert-manager.io/issuer: {{ default "stack-default-certificate-issuer" .Values.tls.issuerName }}
    {{- end }}
    certmanager.k8s.io/acme-challenge-type: {{ default "http01" .Values.tls.acmeChallengeType }}
